[project]
name = "promptcode-data"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "firecrawl>=1.15.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cogflows_justlisten_logic"] 
